# Generated by Django 3.2.9 on 2021-11-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassesment',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
